### ISSUE TITLE
Pod Install error

### ISSUE THREAD

**Issue by ryeo** [ushisantoasobu/Yashin#7]
Hi,

tried to pod install in example directory....using Pods 0.39.

[!] Unable to satisfy the following requirements:
- `Yashin (from`../`)` required by `Podfile`
- `Yashin (from`../`)` required by `Podfile`
  Specs satisfying the `Yashin (from`../`)` dependency were found, but they required a higher minimum deployment target.

**Comment by ushisantoasobu** [comment]
@ryeo Thank you for issue report. :+1: 
I fixed.
